from __future__ import annotations

from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[2]
BUILTINS_PATH = ROOT / "crates/clove-build-core/src/builtins.rs"
VM_PATH = ROOT / "crates/clove-build-core/src/vm/mod.rs"
CODEGEN_PATH = ROOT / "crates/clove-build-core/src/codegen.rs"
# Written under tmp/ (git-ignored): the report is a snapshot of the
# current tree, not a document worth versioning.
OUT_PATH = ROOT / "tmp/phase2_vm_build_matrix.md"


def read_builtins() -> list[str]:
    builtins: list[str] = []
    collecting = False
    for line in BUILTINS_PATH.read_text().splitlines():
        if "BUILTIN_NAMES" in line:
            collecting = True
        if collecting:
            builtins.extend(re.findall(r'"([^"]+)"', line))
        if collecting and line.strip().endswith("];"):
            break
    return builtins


def slice_between(text: str, start: str, end: str) -> str:
    start_idx = text.find(start)
    if start_idx == -1:
        raise RuntimeError(f"{start} not found")
    end_idx = text.find(end, start_idx)
    if end_idx == -1:
        raise RuntimeError(f"{end} not found")
    return text[start_idx:end_idx]


def slice_fn_block(text: str, fn_name: str) -> str:
    start = text.find(f"fn {fn_name}")
    if start == -1:
        raise RuntimeError(f"fn {fn_name} not found")
    # find next function after start
    m = re.search(r"\nfn [A-Za-z_]", text[start + 1 :])
    if not m:
        return text[start:]
    end = start + 1 + m.start()
    return text[start:end]


def main() -> None:
    builtins = read_builtins()
    builtins_set = set(builtins)

    vm_text = VM_PATH.read_text()
    codegen_text = CODEGEN_PATH.read_text()

    call_builtin_vm_block = slice_between(vm_text, "fn call_builtin_vm", "fn call_value_vm")
    compile_expr_block = slice_between(vm_text, "fn compile_expr", "fn compile_bindings")

    cbv_strings = set(re.findall(r'"([^"]+)"', call_builtin_vm_block))
    compile_strings = set(re.findall(r'"([^"]+)"', compile_expr_block))
    vm_fast = sorted((cbv_strings | compile_strings) & builtins_set)
    vm_fast_set = set(vm_fast)

    emit_native_call_block = slice_fn_block(codegen_text, "emit_native_call")
    codegen_strings = set(re.findall(r'"([^"]+)"', emit_native_call_block))
    codegen_builtins = sorted(codegen_strings & builtins_set)
    codegen_set = set(codegen_builtins)

    out: list[str] = []
    out.append("# Build vs VM Coverage (builtins)")
    out.append("")
    out.append("note: generated by tools/phase2/vm_build_matrix.py")
    out.append("")
    out.append(f"- phase2 builtins (BUILTIN_NAMES): {len(builtins_set)}")
    out.append(f"- native codegen builtins: {len(codegen_set)} ({len(codegen_set)/len(builtins_set)*100:.1f}%)")
    out.append(f"- VM fast-path builtins: {len(vm_fast_set)} ({len(vm_fast_set)/len(builtins_set)*100:.1f}%)")
    out.append("")
    out.append("## Matrix")
    out.append("")
    out.append("| builtin | native codegen | VM fast-path |")
    out.append("| --- | --- | --- |")
    for name in sorted(builtins_set):
        out.append(
            f"| `{name}` | {'yes' if name in codegen_set else 'no'} | {'yes' if name in vm_fast_set else 'no'} |"
        )

    OUT_PATH.write_text("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
