from __future__ import annotations

from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[2]

BUILTINS_PATH = ROOT / "crates/clove-build-core/src/builtins.rs"
VM_PATH = ROOT / "crates/clove-build-core/src/vm/mod.rs"
# Written under tmp/ (git-ignored): the report is a snapshot of the
# current tree, not a document worth versioning.
OUT_PATH = ROOT / "tmp/phase2_vm_coverage.md"


def read_builtins() -> list[str]:
    builtins: list[str] = []
    collecting = False
    for line in BUILTINS_PATH.read_text().splitlines():
        if "BUILTIN_NAMES" in line:
            collecting = True
        if collecting:
            builtins.extend(re.findall(r'"([^"]+)"', line))
        if collecting and line.strip().endswith("];"):
            break
    return builtins


def slice_between(text: str, start: str, end: str) -> str:
    start_idx = text.find(start)
    if start_idx == -1:
        raise RuntimeError(f"{start} not found")
    end_idx = text.find(end, start_idx)
    if end_idx == -1:
        raise RuntimeError(f"{end} not found")
    return text[start_idx:end_idx]


def main() -> None:
    vm_text = VM_PATH.read_text()
    builtins = read_builtins()
    builtins_set = set(builtins)

    call_builtin_vm_block = slice_between(vm_text, "fn call_builtin_vm", "fn call_value_vm")
    compile_expr_block = slice_between(vm_text, "fn compile_expr", "fn compile_bindings")

    cbv_strings = set(re.findall(r'"([^"]+)"', call_builtin_vm_block))
    compile_strings = set(re.findall(r'"([^"]+)"', compile_expr_block))

    cbv_builtins = sorted(cbv_strings & builtins_set)
    compile_builtins = sorted(compile_strings & builtins_set)

    vm_fast = sorted(set(cbv_builtins) | set(compile_builtins))
    vm_fast_set = set(vm_fast)
    missing = sorted(builtins_set - vm_fast_set)

    only_cbv = sorted(set(cbv_builtins) - set(compile_builtins))
    only_compile = sorted(set(compile_builtins) - set(cbv_builtins))

    out: list[str] = []
    out.append("# VM Coverage (builtins)")
    out.append("")
    out.append("note: generated by tools/phase2/vm_coverage.py")
    out.append("")
    out.append(f"- phase2 builtins (BUILTIN_NAMES): {len(builtins_set)}")
    out.append(f"- VM fast-path builtins: {len(vm_fast_set)} ({len(vm_fast_set)/len(builtins_set)*100:.1f}%)")
    out.append(
        f"- VM fallback (Value-based) builtins: {len(missing)} ({len(missing)/len(builtins_set)*100:.1f}%)"
    )
    out.append("")

    out.append("## VM fast-path (call_builtin_vm only)")
    out.append("")
    out += [f"- {name}" for name in only_cbv] or ["- (none)"]

    out.append("")
    out.append("## VM fast-path (bytecode opcode only)")
    out.append("")
    out += [f"- {name}" for name in only_compile] or ["- (none)"]

    out.append("")
    out.append("## VM fast-path (call_builtin_vm + opcode)")
    out.append("")
    out += [f"- {name}" for name in vm_fast]

    out.append("")
    out.append("## VM fallback (Value-based)")
    out.append("")
    out += [f"- {name}" for name in missing]

    OUT_PATH.write_text("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
